# Generated by Django 2.0 on 2017-12-06 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('fullName', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('accountCreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
