# Generated by Django 2.0 on 2017-12-06 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171206_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountCreatedDate',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
